# Generated by Django 5.1.5 on 2025-02-01 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_first_name_customer_given_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='given_name',
            new_name='first_name',
        ),
    ]
