# Generated by Django 5.1.5 on 2025-02-01 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_given_name_customer_first_name'),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO store_collection (title)
            VALUES('collection1')
            """,
            """
            DELETE FROM store_collection
            WHERE title='collection1' 
            """

        )
    ]
